# Generated by Django 5.2 on 2025-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_curso_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='celular',
            field=models.CharField(max_length=13),
        ),
    ]
