# Generated by Django 5.2 on 2025-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_estudante_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='celular',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
